package frc.robot.Subsystems;

import edu.wpi.first.math.util.Units;
import edu.wpi.first.networktables.GenericEntry;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.shuffleboard.BuiltInLayouts;
import edu.wpi.first.wpilibj.shuffleboard.BuiltInWidgets;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardLayout;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

public class LimelightSubsystem extends SubsystemBase {
    // NetworkTable to communicate with the Limelight device.
    private NetworkTable networkTable;

    // NetworkTableEntries to obtain various data from the Limelight device.
    private NetworkTableEntry pipelineEntry;
    private NetworkTableEntry camModeEntry;
    private NetworkTableEntry ledModeEntry;
    private NetworkTableEntry horizontalEntry;
    private NetworkTableEntry verticalEntry;
    private NetworkTableEntry targetAreaEntry;
    private NetworkTableEntry foundTagEntry;

    // Shuffleboard tab specifically for the Limelight.
    private ShuffleboardTab limelightTab;
    // Shuffleboard data that can be manipulated.
    private GenericEntry ledStatusEntry;
    private GenericEntry cameraStatusEntry;
    private GenericEntry pipelineIdEntry;

    // Variable to store the current pipeline of the Limelight.
    private double currentPipelineId;

    // Variables to store the current state of the Limelight.
    private boolean isCameraModeOn;
    private boolean isLedOn;

    // Variables to store the angles generated by the tracked object.
    private double horizontalTargetAngle;
    private double verticalTargetAngle;
    private double targetArea;

    // Variables for object detection.
    private double foundTag;
    private boolean foundTagBool;

    // Variables for distance calculations.
    private boolean useTrigForDistanceCalc;
    private double targetAreaDistance;
    private double trigDistance;
    private double distance;

    // Variables for Limelight trigonometry calculations.
    private double limelightAngle;
    private double limelightLensHeight;
    private double goalHeightCentimers;

    // Variables for camera resolution.
    private double horizontalResolution;
    private double verticalResolution;

    /**
     * The LimelightSubsystem constructor. Initializes the Limelight subsystem and
     * sets up the NetworkTable.
     * 
     * @param currentPipelineId      The ID of the current pipeline
     * @param isLedOn                Whether the LED is on
     * @param isCameraModeOn         Whether the camera is in vision mode
     * @param limelightAngle         The mount angle of the Limelight
     * @param limelightLensHeight    The height of the Limelight lens in centimers
     * @param goalHeightCentimers    The height of the goal in centimeters
     * @param horizontalResolution   The horizontal resolution of the camera in px
     * @param verticalResolution     The vertical resolution of the camera in px
     * @param useTrigForDistanceCalc Whether to use trigonometry for distance
     *                               calculations
     */
    public LimelightSubsystem(double currentPipelineId, boolean isLedOn, boolean isCameraModeOn, double limelightAngle,
            double limelightLensHeight, double goalHeightCentimeters, double horizontalResolution,
            double verticalResolution, boolean useTrigForDistanceCalc) {
        this.currentPipelineId = currentPipelineId;
        this.isLedOn = isLedOn;
        this.isCameraModeOn = isCameraModeOn;

        this.limelightAngle = limelightAngle;
        this.limelightLensHeight = limelightLensHeight;
        this.goalHeightCentimers = goalHeightCentimeters;

        this.horizontalResolution = horizontalResolution;
        this.verticalResolution = verticalResolution;

        this.useTrigForDistanceCalc = useTrigForDistanceCalc;

        networkTable = NetworkTableInstance.getDefault().getTable("limelight");

        limelightTab = Shuffleboard.getTab("Limelight");
        ShuffleboardLayout limelightLayout = limelightTab
                .getLayout("Limelight Subsystem Specifications", BuiltInLayouts.kList).withSize(2, 3)
                .withPosition(3, 0);

        ledStatusEntry = limelightTab.add("Set LED Status", this.isLedOn)
                .withWidget(BuiltInWidgets.kToggleButton).getEntry();

        cameraStatusEntry = limelightTab.add("Set Camera Status", this.isCameraModeOn)
                .withWidget(BuiltInWidgets.kToggleButton).getEntry();

        pipelineIdEntry = limelightTab.add("Set Pipeline", this.currentPipelineId)
                .withWidget(BuiltInWidgets.kNumberSlider).getEntry();

        limelightTab.addNumber("Horizontal Resolution", () -> this.horizontalResolution);
        limelightTab.addNumber("Vertical Resolution", () -> this.verticalResolution);
        limelightTab.addNumber("Limelight Lens Height", () -> this.limelightLensHeight);
        limelightTab.addNumber("Limelight Angle", () -> this.limelightAngle);
        limelightTab.addNumber("Goal Height", () -> this.goalHeightCentimers);

        limelightLayout.addNumber("Horizontal Target Angle", () -> getHorizontalTargetAngle());
        limelightLayout.addNumber("Vertical Target Angle", () -> getVerticalTargetAngle());
        limelightLayout.addNumber("Target Area Distance", () -> getTargetAreaDistance());
        limelightLayout.addNumber("Trigonometric Distance", () -> getTrigDistance());
        limelightLayout.addNumber("Preferred Distance", () -> getDistance());
        limelightLayout.addBoolean("Tag Found", () -> getFoundTag());
        limelightLayout.addBoolean("LED Status", () -> getLEDStatus());
        limelightLayout.addBoolean("Camera Status", () -> getCameraModeStatus());
    }

    @Override
    public void periodic() {
        // NetworkTableEntries to store the values generated by the Limelight.
        pipelineEntry = networkTable.getEntry("pipeline");
        camModeEntry = networkTable.getEntry("camMode");
        ledModeEntry = networkTable.getEntry("ledMode");
        horizontalEntry = networkTable.getEntry("tx");
        targetAreaEntry = networkTable.getEntry("ta");
        verticalEntry = networkTable.getEntry("ty");
        foundTagEntry = networkTable.getEntry("tv");

        // Using the entries to generate data and/or change current Limelight
        // specifications.
        pipelineEntry.setNumber(currentPipelineId);
        if (isCameraModeOn) {
            camModeEntry.setNumber(1);
        } else {
            camModeEntry.setNumber(0);
        }
        if (isLedOn) {
            ledModeEntry.setNumber(3);
        } else {
            ledModeEntry.setNumber(1);
        }
        horizontalTargetAngle = horizontalEntry.getDouble(0.0);
        verticalTargetAngle = verticalEntry.getDouble(0.0);
        targetArea = targetAreaEntry.getDouble(0.0);
        foundTag = foundTagEntry.getDouble(0.0);
        foundTagBool = (foundTag != 0) ? true : false;

        // Using data points and trigonometry for distance calculations from the
        // Limelight to the object detected.
        targetAreaDistance = Units.inchesToMeters(54.4 * Math.pow(targetArea, -0.475));
        trigDistance = Units.inchesToMeters(
                (goalHeightCentimers - limelightLensHeight)
                        / Math.tan(Math.toRadians(verticalTargetAngle + limelightAngle)));
        distance = (useTrigForDistanceCalc) ? trigDistance : targetAreaDistance;

        // Horizontal Distance from the Limelight cross hair to the object detected in
        // meters and pixels.
        double horizontalDistance = Math.tan(Math.toRadians(horizontalTargetAngle)) * distance;
        double verticalDistance = Math.tan(Math.toRadians(verticalTargetAngle)) * distance;
        double cameraPixelX = horizontalTargetAngle / 59.6 * horizontalResolution;
        double cameraPixelY = verticalTargetAngle / 49.7 * verticalResolution;
        double cameraPixeltargetArea = targetArea / 100 * horizontalResolution * verticalResolution;
    }

    /**
     * Getter methods for various values in the LimelightSubsystem
     * 
     * @return The current value of the property
     */
    public double getHorizontalTargetAngle() {
        return horizontalTargetAngle;
    }

    public double getVerticalTargetAngle() {
        return verticalTargetAngle;
    }

    public double getTargetAreaDistance() {
        return targetAreaDistance;
    }

    public double getTrigDistance() {
        return trigDistance;
    }

    public double getDistance() {
        return distance;
    }

    public boolean getFoundTag() {
        return foundTagBool;
    }

    public boolean getLEDStatus() {
        return isLedOn;
    }

    public boolean getCameraModeStatus() {
        return isCameraModeOn;
    }

    public double getCurrentPipelineId() {
        return currentPipelineId;
    }

    /**
     * Setter methods to change the values of various properties in the
     * LimelightSubsystem
     * 
     * @param newValue The new value to set
     */
    public void setLEDStatus(boolean isLedOn) {
        this.isLedOn = isLedOn;
    }

    public void setCameraStatus(boolean isCameraModeOn) {
        this.isCameraModeOn = isCameraModeOn;
    }

    public void setPipelineId(double currentPipelineId) {
        this.currentPipelineId = currentPipelineId;
    }
}
